### ISSUE TITLE
The code link is broken

### ISSUE THREAD

**Issue by focusright** [PacktPublishing/Hands-On-Artificial-Intelligence-with-Unreal-Engine#1]
This link is broken: 

http://hog.red/AIBook2019ProjectFiles

**Comment by fsapio** [comment]
Thanks for pointing it out.
I will investigate the issue, and restore the link in the next couple of days.

**Comment by fsapio** [comment]
Dear Mike Lee @focusright ,

The link has been fixed. Please, let me know if you have any other issue.

**Comment by focusright** [comment]
It works now, thanks. One suggestion, maybe upload the files to this repo?

**Comment by fsapio** [comment]
I would if the projects were in C++ only. However, there is a base of Blueprint users, so I have to include Binaries as well in the projects. There is no problem in including Binaries in the repo, however, Blueprint users needs binary for each specific version of the engine.
In any case, it was something I considered, but I will give it a second thought, thanks.
